# ONE traversal, used by both the capture script and the checker, so the order of
# every array below is the same on both sides by construction.  Nothing here
# judges anything: it only lays the state out.
#
# `SLCE` is substituted at generation time; the two packages' payloads differ
# only in the constructor names and in how a key's per-site spin ranks are read.

using SLCE
using SLCE: spin_ls, build_neighbor_list, build_clusters, evaluate_salc, solve_coefficients, n_ops
# Loaded, not imported: the package only needs the extension to trigger, and
# Spglib exports `Crystal` / `Lattice`, which would shadow the ones under test.
import Spglib
using LinearAlgebra, Random, TOML

const PIN_SCHEMA = 1
const PIN_EPS = 5.0e-6      # see PIN.md "the L0' threshold" -- measured, not chosen

hexf(v::Float64)::String = string(reinterpret(UInt64, v); base = 16, pad = 16)
unhexf(s::AbstractString)::Float64 = reinterpret(Float64, parse(UInt64, s; base = 16))

_pin_ls(k) = spin_ls(k)

function pin_basis(fx)
    cr = Crystal(Lattice(fx.L), fx.frac, fx.species, fx.labels)
    spec = BasisSpec(cr; nbody = fx.nbody, lmax = fx.lmax, cutoff = fx.cutoff, soc = true)
    return SLCEBasis(cr, spec; backend = SpglibBackend())
end

# A seeded configuration stream.  The RNG and its draw order are part of the pin:
# change either and every L2 number moves, which is a recapture, not a bug.
function pin_configs(nat::Int, m::Int, seed::Int)
    rng = MersenneTwister(seed)
    return [begin
                e = Matrix{Float64}(undef, 3, nat)
                for a = 1:nat
                    v = randn(rng, 3)
                    e[:, a] = v / norm(v)
                end
                e
            end for _ = 1:m]
end

function pin_payload(fx)::Dict{String,Any}
    B = pin_basis(fx)
    sb = B.salc_basis
    nat = n_atoms(B.crystal)

    keys_, mems, terms, support, folded = String[], String[], String[], String[], String[]
    for (c, s) in enumerate(sb.salcs)
        k = sb.keys[c]
        push!(keys_, string(k.body, " ", k.orbit_id, " [", join(_pin_ls(k), ","), "] ",
                            k.Lf, " ", k.block))
        for (mi, m) in enumerate(s.members)
            push!(mems, string(c, " ", mi, " [", join(m.atoms, ","), "] ",
                               join("(" * join(v, ",") * ")" for v in m.shifts)))
            for (ti, t) in enumerate(m.terms)
                lst = Int[sl.factor.l for sl in t.slots]
                push!(terms, string(c, " ", mi, " ", ti, " [", join(lst, ","), "] [",
                                    join(size(t.folded), ","), "]"))
                push!(support, join(abs(v) <= PIN_EPS ? '.' : (v > 0 ? '+' : '-')
                                    for v in t.folded))
                for v in t.folded
                    push!(folded, hexf(v))
                end
            end
        end
    end

    # L2: the design matrix and a full OLS round trip.  The targets are a SEEDED
    # RANDOM vector, deliberately NOT generated by pushing a coefficient vector
    # through this same basis: that round trip cancels, and a uniform rescale of
    # the whole basis would leave `coef` and `r2` numerically identical (measured
    # 2026-08-21 -- only `design_frob2` and `heldout` moved). Fitting an arbitrary
    # target makes every number here move when the design matrix moves.
    #
    # This layer detects CHANGE in the whole pipeline (assembly + solve + read
    # back); it is not evidence that any of the three is correct, and `coef` is
    # gauge-dependent, so a legitimate gauge change trips L2 and only L2.
    p = length(sb.salcs)
    cfgs = pin_configs(nat, 4p + 20, 20260821)
    rng = MersenneTwister(20260823)
    energies = randn(rng, length(cfgs))
    ds = SLCEDataset(B, cfgs, energies)
    f = fit(SLCEFit, ds, OLS())
    held = pin_configs(nat, 10, 20260822)

    return Dict{String,Any}(
        "schema" => PIN_SCHEMA,
        "fixture" => Dict{String,Any}("id" => fx.id, "nbody" => fx.nbody,
                                      "lmax" => collect(fx.lmax),
                                      "cutoff" => fx.cutoff,
                                      "n_ops" => n_ops(B.spacegroup),
                                      "n_atoms" => nat),
        "L0" => Dict{String,Any}("n_salcs" => p, "keys" => keys_,
                                 "members" => mems, "terms" => terms),
        "L0prime" => Dict{String,Any}("eps" => PIN_EPS, "support" => support),
        "L1" => Dict{String,Any}("folded" => folded),
        "L2" => Dict{String,Any}(
            "design_frob2" => hexf(sum(abs2, ds.X_E)),
            "r2" => hexf(r2(f)),
            "coef" => hexf.(coef(f)),
            "heldout" => hexf.(predict_energy(SLCEModel(B, intercept(f), coef(f)), held))),
    )
end
